[workspace]
members = [
    "programs/*",
    "encrypted-ixs"
]
resolver = "2"

[workspace.package]
license = "Apache-2.0"
repository = "https://github.com/VelaPay/vela-protocol"

[workspace.dependencies]
proptest = "1"

[profile.release]
overflow-checks = true
lto = "fat"
codegen-units = 1
[profile.release.build-override]
opt-level = 3
incremental = false
codegen-units = 1
