//! Tests for ARCM-01 (comp_def initialization) and ARCM-02 (config initialization).
//!
//! Note: Full Arcium MXE integration tests require a running Arcium cluster (Docker).
//! These tests verify:
//! - ARCM-01: The init_validate_mandate_comp_def instruction is properly wired and can be invoked
//! - ARCM-02: ProtocolConfig PDA initialization and update with admin-only access control

#[path = "helpers/mod.rs"]
mod helpers;

use anchor_lang::prelude::Pubkey;
use anchor_lang::{InstructionData, ToAccountMetas};
use helpers::{arcium_helpers::derive_config_pda, to_address, to_anchor_pubkey, TestHarness};
use solana_instruction::{AccountMeta, Instruction};
use solana_message::{Message, VersionedMessage};
use solana_signer::Signer;
use solana_transaction::versioned::VersionedTransaction;
use vela_protocol::instruction::{InitConfig, InitValidateMandateCompDef, UpdateConfig};
use vela_protocol::state::ClusterType;

/// ARCM-01: Test that the init_validate_mandate_comp_def instruction can be invoked.
///
/// Since actual Arcium MXE initialization requires a running Arcium cluster,
/// this test verifies the instruction accounts can be constructed correctly
/// and the instruction discriminator is generated by the program.
///
/// This is a structural verification: the instruction exists in the compiled
/// program's IDL and can be invoked with the correct account structure.
#[test]
fn test_comp_def_init() {
    // Build the program first (this runs as part of the test suite setup)
    let _harness = TestHarness::new();

    // Check that the IDL contains the init_validate_mandate_comp_def instruction
    // by attempting to construct the instruction data
    let ix_data = InitValidateMandateCompDef {}.data();
    assert!(
        !ix_data.is_empty(),
        "init_validate_mandate_comp_def instruction should have a discriminator"
    );

    // Test passes if we reach here: the instruction and accounts struct exist
    let _ = ix_data;
    println!("test_comp_def_init passed: instruction discriminator exists");
}

/// ARCM-02: Test ProtocolConfig initialization with Cerberus cluster.
#[test]
fn test_config_init() {
    let mut harness = TestHarness::new();
    let admin = harness.create_wallet();
    let program_id = to_anchor_pubkey(harness.program_id);

    // Random cluster pubkey for testing
    let cluster_pubkey = Pubkey::new_unique();

    // Derive the config PDA
    let config_pda = derive_config_pda(&program_id);

    // Build init_config instruction
    let accounts = vela_protocol::accounts::InitConfig {
        admin: to_anchor_pubkey(admin.pubkey()),
        config: config_pda,
        system_program: anchor_lang::system_program::ID,
    };

    // Use the instruction data wrapper with ix field
    let instruction_data = InitConfig {
        ix: vela_protocol::instructions::init_config::InitConfigIx {
            cluster_pubkey,
            cluster_type: ClusterType::Cerberus,
            cluster_offset: 456,
        },
    }
    .data();

    let instruction = Instruction {
        program_id: harness.program_id,
        accounts: accounts_to_meta(accounts.to_account_metas(None)),
        data: instruction_data,
    };

    // Send the transaction
    let blockhash = harness.svm.latest_blockhash();
    let message = Message::new_with_blockhash(&[instruction], Some(&admin.pubkey()), &blockhash);
    let tx = VersionedTransaction::try_new(VersionedMessage::Legacy(message), &[&admin])
        .expect("transaction should sign");

    let result = harness.svm.send_transaction(tx);
    assert!(
        result.is_ok(),
        "init_config should succeed: {:?}",
        result.err()
    );

    // Verify the ProtocolConfig PDA was created with correct values
    let config: vela_protocol::state::ProtocolConfig = harness.fetch_anchor_account(&config_pda);
    assert_eq!(
        config.admin,
        to_anchor_pubkey(admin.pubkey()),
        "admin should match the signer"
    );
    assert_eq!(
        config.cluster_pubkey, cluster_pubkey,
        "cluster_pubkey should match input"
    );
    assert_eq!(
        config.cluster_type,
        ClusterType::Cerberus,
        "cluster_type should be Cerberus"
    );
    assert_eq!(
        config.cluster_offset, 456,
        "cluster_offset should be 456 (devnet default)"
    );
    assert!(config.bump != 0, "bump should be non-zero");

    println!("test_config_init passed: ProtocolConfig initialized correctly");
}

/// ARCM-02: Test that admin can update the ProtocolConfig.
#[test]
fn test_config_update_by_admin() {
    let mut harness = TestHarness::new();
    let admin = harness.create_wallet();
    let program_id = to_anchor_pubkey(harness.program_id);

    // First initialize the config
    let cluster_pubkey_initial = Pubkey::new_unique();
    let config_pda = derive_config_pda(&program_id);

    // Initialize
    let init_accounts = vela_protocol::accounts::InitConfig {
        admin: to_anchor_pubkey(admin.pubkey()),
        config: config_pda,
        system_program: anchor_lang::system_program::ID,
    };

    let init_instruction_data = InitConfig {
        ix: vela_protocol::instructions::init_config::InitConfigIx {
            cluster_pubkey: cluster_pubkey_initial,
            cluster_type: ClusterType::Cerberus,
            cluster_offset: 456,
        },
    }
    .data();

    let init_instruction = Instruction {
        program_id: harness.program_id,
        accounts: accounts_to_meta(init_accounts.to_account_metas(None)),
        data: init_instruction_data,
    };

    let blockhash = harness.svm.latest_blockhash();
    let message =
        Message::new_with_blockhash(&[init_instruction], Some(&admin.pubkey()), &blockhash);
    let tx = VersionedTransaction::try_new(VersionedMessage::Legacy(message), &[&admin])
        .expect("transaction should sign");
    harness
        .svm
        .send_transaction(tx)
        .expect("init_config should succeed");

    // Now update the config
    let new_cluster_pubkey = Pubkey::new_unique();

    let update_accounts = vela_protocol::accounts::UpdateConfig {
        admin: to_anchor_pubkey(admin.pubkey()),
        config: config_pda,
    };

    let update_instruction_data = UpdateConfig {
        ix: vela_protocol::instructions::init_config::UpdateConfigIx {
            cluster_pubkey: new_cluster_pubkey,
            cluster_type: ClusterType::Manticore,
            cluster_offset: 999,
        },
    }
    .data();

    let update_instruction = Instruction {
        program_id: harness.program_id,
        accounts: accounts_to_meta(update_accounts.to_account_metas(None)),
        data: update_instruction_data,
    };

    harness.svm.expire_blockhash();
    let blockhash = harness.svm.latest_blockhash();
    let message =
        Message::new_with_blockhash(&[update_instruction], Some(&admin.pubkey()), &blockhash);
    let tx = VersionedTransaction::try_new(VersionedMessage::Legacy(message), &[&admin])
        .expect("transaction should sign");
    harness
        .svm
        .send_transaction(tx)
        .expect("update_config should succeed");

    // Verify the update
    let config: vela_protocol::state::ProtocolConfig = harness.fetch_anchor_account(&config_pda);
    assert_eq!(
        config.cluster_pubkey, new_cluster_pubkey,
        "cluster_pubkey should be updated"
    );
    assert_eq!(
        config.cluster_type,
        ClusterType::Manticore,
        "cluster_type should be Manticore"
    );
    assert_eq!(config.cluster_offset, 999, "cluster_offset should be 999");

    println!("test_config_update_by_admin passed: ProtocolConfig updated correctly");
}

/// ARCM-02: Test that non-admin cannot update the ProtocolConfig.
#[test]
fn test_config_update_by_non_admin_fails() {
    let mut harness = TestHarness::new();
    let admin = harness.create_wallet();
    let non_admin = harness.create_wallet();
    let program_id = to_anchor_pubkey(harness.program_id);

    // First initialize the config with admin
    let config_pda = derive_config_pda(&program_id);

    let init_accounts = vela_protocol::accounts::InitConfig {
        admin: to_anchor_pubkey(admin.pubkey()),
        config: config_pda,
        system_program: anchor_lang::system_program::ID,
    };

    let init_instruction_data = InitConfig {
        ix: vela_protocol::instructions::init_config::InitConfigIx {
            cluster_pubkey: Pubkey::new_unique(),
            cluster_type: ClusterType::Cerberus,
            cluster_offset: 456,
        },
    }
    .data();

    let init_instruction = Instruction {
        program_id: harness.program_id,
        accounts: accounts_to_meta(init_accounts.to_account_metas(None)),
        data: init_instruction_data,
    };

    let blockhash = harness.svm.latest_blockhash();
    let message =
        Message::new_with_blockhash(&[init_instruction], Some(&admin.pubkey()), &blockhash);
    let tx = VersionedTransaction::try_new(VersionedMessage::Legacy(message), &[&admin])
        .expect("transaction should sign");
    harness
        .svm
        .send_transaction(tx)
        .expect("init_config should succeed");

    // Try to update with non_admin - should fail
    let update_accounts = vela_protocol::accounts::UpdateConfig {
        admin: to_anchor_pubkey(non_admin.pubkey()),
        config: config_pda,
    };

    let update_instruction_data = UpdateConfig {
        ix: vela_protocol::instructions::init_config::UpdateConfigIx {
            cluster_pubkey: Pubkey::new_unique(),
            cluster_type: ClusterType::Manticore,
            cluster_offset: 999,
        },
    }
    .data();

    let update_instruction = Instruction {
        program_id: harness.program_id,
        accounts: accounts_to_meta(update_accounts.to_account_metas(None)),
        data: update_instruction_data,
    };

    harness.svm.expire_blockhash();
    let blockhash = harness.svm.latest_blockhash();
    // Use non_admin as the fee payer
    let message =
        Message::new_with_blockhash(&[update_instruction], Some(&non_admin.pubkey()), &blockhash);
    let tx = VersionedTransaction::try_new(VersionedMessage::Legacy(message), &[&non_admin])
        .expect("transaction should sign");
    let result = harness.svm.send_transaction(tx);

    // The transaction should fail (UnauthorizedAdmin error)
    assert!(result.is_err(), "update_config with non-admin should fail");

    println!("test_config_update_by_non_admin_fails passed: non-admin correctly rejected");
}

/// ARCM-02: Structural verification that the encrypted-ixs crate compiles.
///
/// This test verifies that the encrypted-ixs crate is part of the workspace
/// and compiles without errors. The actual circuit compilation would require
/// `arcium build` which needs Docker.
#[test]
fn test_encrypted_circuit_compiles() {
    // Verify the encrypted-ixs crate is in the workspace by checking
    // that we can import from it (the crate compiles as part of the test run)
    //
    // Note: The actual Arcis circuit compilation requires `arcium build`
    // which needs Docker. This test verifies the Rust source compiles.

    // We verify compilation by checking the workspace check succeeds
    // In practice, this test passes because cargo test compiles the entire workspace first
    let result = std::process::Command::new("cargo")
        .args(["check", "-p", "encrypted-ixs"])
        .current_dir(std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../.."))
        .output();

    assert!(
        result.is_ok(),
        "encrypted-ixs crate should compile: {:?}",
        result.err()
    );
    assert!(
        result.unwrap().status.success(),
        "encrypted-ixs cargo check should succeed"
    );

    println!("test_encrypted_circuit_compiles passed: encrypted-ixs crate compiles");
}

fn accounts_to_meta(
    metas: Vec<anchor_lang::solana_program::instruction::AccountMeta>,
) -> Vec<AccountMeta> {
    metas
        .into_iter()
        .map(|meta| {
            if meta.is_writable {
                AccountMeta::new(to_address(meta.pubkey), meta.is_signer)
            } else {
                AccountMeta::new_readonly(to_address(meta.pubkey), meta.is_signer)
            }
        })
        .collect()
}
