[package]
name = "vela-protocol"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "lib"]
name = "vela_protocol"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build", "arcium-anchor/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = { version = "=0.32.1", features = ["init-if-needed"] }
anchor-spl = "=0.32.1"
arcium-anchor = "0.9.3"
arcium-macros = "0.9.3"
arcium-client = { version = "0.9.3", default-features = false }
spl-token-2022 = { version = "10.0.0", features = ["no-entrypoint"] }
spl-token-metadata-interface = "0.8.0"
spl-pod = "=0.7.1"
spl-token-group-interface = "=0.7.1"
spl-transfer-hook-interface = "=2.0.0"
solana-instruction = "=3.3.0"
solana-program-error = "=3.0.1"
solana-pubkey = "=3.0.0"

[dev-dependencies]
litesvm = "0.10.0"
litesvm-token = "*"
solana-sdk = "*"
solana-address = "=2.5.0"
solana-account = "=3.4.0"
solana-clock = "=3.0.0"
solana-keypair = "=3.1.0"
solana-message = "=3.1.0"
solana-program-pack = "=3.0.0"
solana-signer = "=3.0.0"
solana-system-interface = { version = "=2.0.0", features = ["bincode"] }
solana-transaction = { version = "=3.1.0", features = ["verify"] }
spl-token = "*"
spl-associated-token-account = "*"

[build-dependencies]
serde_json = "1"

[[test]]
name = "test_create_plan"
path = "../../tests/test_create_plan.rs"

[[test]]
name = "test_subscribe"
path = "../../tests/test_subscribe.rs"

[[test]]
name = "test_execute_pull"
path = "../../tests/test_execute_pull.rs"

[[test]]
name = "test_cancel"
path = "../../tests/test_cancel.rs"

[[test]]
name = "test_edge_cases"
path = "../../tests/test_edge_cases.rs"

[[test]]
name = "test_cu_profiling"
path = "../../tests/test_cu_profiling.rs"

[[test]]
name = "test_credential"
path = "../../tests/test_credential.rs"

[[test]]
name = "test_arcium_validation"
path = "../../tests/test_arcium_validation.rs"

[[test]]
name = "test_fail_closed"
path = "../../tests/test_fail_closed.rs"

[[test]]
name = "test_pull_approval"
path = "../../tests/test_pull_approval.rs"

[[test]]
name = "test_billing_event"
path = "../../tests/test_billing_event.rs"


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
